@define[PPT_PAGE_TITLE:WotScript About]
@define[PPT_STYLE_SHEET:"news.css"]
@define[PPT_HOME_ACTIVE:""]
@define[PPT_DOCS_ACTIVE:""]
@define[PPT_ABOUT_ACTIVE:"active"]
@define[PPT_NEWS_ACTIVE:""]
@define[PPT_FAQ_ACTIVE:""]
@define[PPT_PAGE_CONTENT:
@include[../pages/about_c.html]
]
@include[../templates/page_template.html]