@define[PPT_PAGE_TITLE:WotScript FAQ]
@define[PPT_STYLE_SHEET:"faq.css"]
@define[PPT_HOME_ACTIVE:""]
@define[PPT_DOCS_ACTIVE:""]
@define[PPT_ABOUT_ACTIVE:""]
@define[PPT_NEWS_ACTIVE:""]
@define[PPT_FAQ_ACTIVE:"active"]
@define[PPT_PAGE_CONTENT:
@include[../pages/faq_c.html]
]
@include[../templates/page_template.html]